service: auth-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

functions:
  fileHandler:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .git/**
    - .env/**
